exclude: [README, .gitignore]

permalink: /posts/:year/:title.html

author-name: Tom Lowenthal
author-tagline: a paranoid tech policy wonk & security geek with a penchant for personal privacy & individual liberty
author-location: San Francisco
author-img: tom-lowenthal.jpg
author-img-alt: A photograph of the grinning mug of Tom Lowenthal.

username: flamsmark
hostname: homebox

posts-title: Writing
posts-subtitle: Active rhetoric and inaccurate statements

license: CC-BY-SA
license-link: https://creativecommons.org/licenses/by-sa/3.0/us/
